version: '3.9'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://dev:dev@postgres:5432/ticket_system?sslmode=disable
      - JWT_SECRET=e7f9G6jK1T+3N5qXb4uR8pW2YzQ0uV1xZ7aC4dE5fI=
      - SERVER_PORT=8080
      - LOG_LEVEL=debug
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: ticket_system
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d ticket_system"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/migrations:/migration
  adminer:
    image: adminer
    ports:
      - "8081:8080"
volumes:
  db-data:
